name: "Restore cached Docker images"
description: "Loads, or pulls and caches, Docker images."

inputs:
  cache_key:
    required: true
    description: "Key for cache entry."
  cache_path:
    required: true
    description: "Directory to cache and restore."

outputs:
  cache-hit:
    description: "A boolean indicating if the cache has been found."
    value: ${{ steps.cache-docker-image.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: "Restore cache"
      id: cache-docker-image
      uses: actions/cache/restore@v5
      with:
        path: ${{ inputs.cache_path }}
        key: ${{ inputs.cache_key }}

    - name: "Populate cache"
      if: steps.cache-docker-image.outputs.cache-hit != 'true'
      shell: "bash"
      run: ${{github.action_path}}/cacheDockerImages.sh ${{ inputs.cache_path }}

    - name: "Load images"
      if: steps.cache-docker-image.outputs.cache-hit == 'true'
      shell: "bash"
      run: ${{github.action_path}}/loadDockerImages.sh ${{ inputs.cache_path }}
