name: "Save cached Docker images"
description: "Saves and clears cached Docker images."

inputs:
  cache-key:
    required: true
    description: "Key for cache entry."
  cache-path:
    required: true
    description: "Directory to cache and restore."

runs:
  using: "composite"
  steps:
    - name: "Save cache"
      id: cache-docker-image
      uses: actions/cache/save@v5
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-key }}
