name: Resources

on:
  push:
    branches-ignore:
      - main

env:
  FLATPAK_SOURCES_PATH: ./build/flatpak/generated-sources.json

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup tools
        run: |
          sudo apt-get install -y flatpak-builder
          gh repo clone flatpak/flatpak-builder-tools
          (cd flatpak-builder-tools/node && pipx install .)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Generate resources
        run: |
          mkdir -p $(dirname $FLATPAK_SOURCES_PATH)
          flatpak-node-generator npm ./package-lock.json -o $FLATPAK_SOURCES_PATH
